//%%%%%%%%%%    نحوه ی استفاده از استایل ها در NEXT JS %%%%%%%%%%%%%%%%
//%%%%%%******** 1. Global Styles, یا استایل دهی به همه ی تگ های داخل کامپوننت ها بصورت مشترک در داخل فایل global.css
//%%%%%%******** 2. Modular Styles(local Styles), یا استایل دهی به تگ های داخل  تک تک کامپوننت ها بصورت جداگانه در داخل فایل Employers.module.css, Users.module.css, Create.module.css, ...
//%%%%%%%%%%    برای استفاده از استایل ها در NEXT JS, باید در داخل پوشه ی اصلی app, فونت های css, را در داخل فایل global.css, نوشته و در داخل این فایل، با استفاده از کتابخانه های استایل دهی bootstrap, tailwind,... جایگزاری کنیم و در داخل فایل layout.jsx, آن را به صورت import './globals.css'; فراخوانی کنیم که این نوع استایل دهی بر روی همه ی کامپوننت ها اعمال می شود ولی اگر بخواهیم به فایل یا کامپوننت خاصی مثلا فقط کامپوننت employer, استایل دهی کنیم باید ابتدا در داخل پوشه ی styles, یک فایل با نام Employers.module.css, ایجاد کرده و در داخل این فایل استایل های مربوط به کامپوننت employers, را بنویسیم و برای اعمال این استایل ها بر روی کامپوننت employers, باید ابتدا آن را در داخل فایل layout.jsx, با استفاده از import employersStyle from '../styles/Employers.module.css', فراخوانی کرده و در داخل کامپوننت <Employers />, و در بخش کلاس دهی به این کامپوننت، بصورت <Employers className={employersStyle.container}>,  <Employers className={employersStyle.body}>, و برای بقیه ی تگ ها نیز همینطور الی آخر اعمال می کنیم   %%%%%%%%%%%%%%%%
import './styles/globals.css';
// import './globals.css';
// import employersStyle from '../styles/Employers.module.css';
// import Styles from './styles/Layout.module.css;



//%%%%%%%%%%    نحوه ی استفاده از تصاویر، فونت ها و استایل ها در NEXT JS %%%%%%%%%%%%%%%%
//%%%%%%%%%%    نحوه ی استفاده از فونت هادر NEXT JS %%%%%%%%%%%%%%%%
  //%%%%%%%%%%    ما به دو روش: لوکال یا با استفاده از گوگل،  از فونت هادر NEXT JS, استفاده کنیم  %%%%%%%%%%%%%%%%
    //%%%%%%%%%% 1.   با استفاده از import { Inter } from 'next/font/google'; NEXT JS از  تعداد زیادی از فونت های مشهور مورد استفاده در سایت های مختلف را از گوگل دریافت کرده و سپس با استفاده از const inter = Inter({ subsets: ['latin'] }), از روی این یک شی می سازیم و در داخل آن خصوصیاتی همانند: نوع  ونت ، وزن یا سایز فونت و غیره را به آن می   می دهیم و در داخل تگها هنگام کلاس دادن به آن تگ، از این فونت بصورت bfjjmgh,  و در داخل سرور وبسایت ما ذخیره می کند تا بتوانیم از آنها در وبسایتمان استفاده کنیم  %%%%%%%%%%%%%%%%
    //%%%%%%%%%% 2.   با استفاده از import { fontName } from './fonts/';  NEXT JS از فونت هایی که در داخل پوشه ی fonts, قرار داده ایم می توانیم در داخل وبسایت از آنهااستفاده کنیم  %%%%%%%%%%%%%%%%
import localFont from 'next/font/local';
const vazirFont = localFont({ 
  src: '../public/font/vazirmatn-v33.003/fonts/ttf/Vazirmatn-Regular.ttf',
})

// import { Rubik } from 'next/font/google';
// const rubik = Rubik({ subsets: ['latin'] })


//%%%%%% components %%%%%%%%%
import Navbar from './content/Navbar';
import Header from './content/Header';
import Footer from './content/Footer';

//%%%%%%%%%%    نحوه ی استفاده از تصاویر در NEXT JS %%%%%%%%%%%%%%%%
//%%%%%%%%%%    برای استفاده از تصاویر در NEXT JS, باید تصاویر را در داخل پوشه ی components, و یا پوشه ی public, قرار دهیم و با فراخوانی کردن آن ها در داخل فایل های مختلف با  از import,  آنها را در فایل های مختلف استفاده کنیم %%%%%%%%%%%%%%%%
// import Image from 'next/image';
// import AdministerImage from './ali.jpg';
// import AdministerImage from './ali.jpg';


//%%%%%%%%%%    نحوه ی استفاده از کد npm run build, در داخل ترمینال vs code, برای بیلد کردن اپلیکیشن نهایی وبسایت خودمان در NEXT JS %%%%%%%%%%%%%%%%



//%%%%%%%% layout component, برای ایجاد صفحه ها یا پیج های مورد استفاده در جاهای مختلف وبسایت همانند Header, Footer, Navbar,... و یا در حالت کای برای ایجاد روت های مختلف و فراخوانی آنها در داخل Next js, از کامپوننت <Layout></Layout>, استفاده می شود
//%%%%%%****  <Layout></Layout>


//%%%%%%%% meta Tags, از متا تگ ها، برای سئو یا SEO, وبسایت و روت های مختلف این وبسایت، برای جستجوی بهتر جستجوگرهای گوگل و غیره با استفاده از کلمه های کلیدی ای که به آن می دهیم ، استفاده می شود
export const metadata = {
  title: 'amirsam-company',
  description: 'Generated by amisam-company that is noce of HighTech Iranian Persian Industrial company that made products like accolators, winding & welding robots,olive pitting and slicing machine, powdwer coating machines cascades,... ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 text-slate-700 ${vazirFont.className}`}>

        <>
          <Navbar />

            <br />

            <div>

              <main>
                <Header />
                {children}
              </main>

            </div>

            <br />

          <Footer />
        </>

      </body>
    </html>
  )
}


